language: erlang
before_install: echo "#!/usr/bin/env bash" > `which rebar`
script: make travis
notifications:
  disabled: true
otp_release:
  - 18.2
  - 18.0
  - 17.5
  - 17.1
  - R16B03
  - R15B03
  - R14B04
