name: ci/cd

on:
  push:
    branches: [ master, release/*, develop]
  pull_request:
    branches: [ master, release/*, develop]

jobs:

  build:
    name: Build on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        otp_version: [19, 20, 21, 22, 23]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile (with make)
      run: make compile
    - name: Install
      run: make install PREFIX=$(mktemp -d)
    - name: Clean make-based Build
      run: make clean
    - name: Compiler (with rebar3)
      run: rebar3 compile
    - name: Run eunit Tests
      run: rebar3 as test eunit
    - name: Run proper Tests
      run: rebar3 as test proper
    - name: CT Suite Tests
      run: rebar3 as test ct
