name: ci/cd

on:
  push:
    branches: [ master, release/*]
  pull_request:
    branches: [ master, release/*]

jobs:

  build:
    name: Build on OTP ${{ matrix.otp_version }} / ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp_version: [19, 20, 21, 22, 23]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make compile
    - name: Install
      run: make install PREFIX=$(mktemp -d)
    - name: Eunit and Prop Tests
      run: rebar3 eunit -m clj-tests,prop_lfe_doc
    - name: CT Suite Tests
      run: rebar3 ct
